jwt:
  secret: authetication-server-jwt-secret

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authentication-db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root
  flyway:
    url: jdbc:mysql://localhost:3306/authentication-db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    user: root
    password: root
    baseline-on-migrate: false